'use strict';

/** From GTFS_SQL_50_Easy_Exercises.docx — titles without numbering */
module.exports = [
  ["Show all routes", ["routes"], `SELECT * FROM routes;`],
  ["Show route_id and route_long_name", ["routes"], `SELECT route_id, route_long_name FROM routes;`],
  ["Show first 10 stops", ["stops"], `SELECT * FROM stops LIMIT 10;`],
  ["Show all trips", ["trips"], `SELECT * FROM trips;`],
  ["Show stop names only", ["stops"], `SELECT stop_name FROM stops;`],
  ["Show route types", ["routes"], `SELECT route_type FROM routes;`],
  ["Show agency info", ["agency"], `SELECT * FROM agency;`],
  ["Show unique route types", ["routes"], `SELECT DISTINCT route_type FROM routes;`],
  ["Show unique stop names", ["stops"], `SELECT DISTINCT stop_name FROM stops;`],
  ["Show first 5 trips", ["trips"], `SELECT * FROM trips LIMIT 5;`],
  ["Find all bus routes", ["routes"], `SELECT * FROM routes WHERE route_type = 3;`],
  ["Find stops containing 'Toronto'", ["stops"], `SELECT * FROM stops WHERE stop_name LIKE '%Toronto%';`],
  ["Trips for route 10", ["trips"], `SELECT * FROM trips WHERE route_id = '10';`],
  ["Stops with latitude > 43.7", ["stops"], `SELECT * FROM stops WHERE stop_lat > 43.7;`],
  ["Stop times for a trip", ["stop_times"], `SELECT * FROM stop_times WHERE trip_id = '1001';`],
  ["Routes starting with 5", ["routes"], `SELECT * FROM routes WHERE route_short_name LIKE '5%';`],
  ["Trips direction 0", ["trips"], `SELECT * FROM trips WHERE direction_id = 0;`],
  ["Stops with 'Station'", ["stops"], `SELECT * FROM stops WHERE stop_name LIKE '%Station%';`],
  ["Trips with WEEKDAY service", ["trips"], `SELECT * FROM trips WHERE service_id = 'WEEKDAY';`],
  ["Stop_times first stops", ["stop_times"], `SELECT * FROM stop_times WHERE stop_sequence = 1;`],
  ["Sort stops by name", ["stops"], `SELECT * FROM stops ORDER BY stop_name;`],
  ["Sort routes descending", ["routes"], `SELECT * FROM routes ORDER BY route_id DESC;`],
  ["Sort trips by route", ["trips"], `SELECT * FROM trips ORDER BY route_id;`],
  ["Sort stops by latitude", ["stops"], `SELECT * FROM stops ORDER BY stop_lat DESC;`],
  ["Sort stop_times", ["stop_times"], `SELECT * FROM stop_times ORDER BY trip_id, stop_sequence;`],
  ["Count routes", ["routes"], `SELECT COUNT(*) FROM routes;`],
  ["Count stops", ["stops"], `SELECT COUNT(*) FROM stops;`],
  ["Trips per route", ["trips"], `SELECT route_id, COUNT(*) FROM trips GROUP BY route_id;`],
  ["Stops per trip", ["stop_times"], `SELECT trip_id, COUNT(*) FROM stop_times GROUP BY trip_id;`],
  ["Distinct route types count", ["routes"], `SELECT COUNT(DISTINCT route_type) FROM routes;`],
  ["Count station stops", ["stops"], `SELECT COUNT(*) FROM stops WHERE stop_name LIKE '%Station%';`],
  ["Max stop_sequence", ["stop_times"], `SELECT MAX(stop_sequence) FROM stop_times;`],
  ["Min stop_sequence", ["stop_times"], `SELECT MIN(stop_sequence) FROM stop_times;`],
  ["Avg stop_sequence", ["stop_times"], `SELECT AVG(stop_sequence) FROM stop_times;`],
  ["Trips per service", ["trips"], `SELECT service_id, COUNT(*) FROM trips GROUP BY service_id;`],
  ["Routes with >10 trips", ["trips"], `SELECT route_id, COUNT(*) FROM trips GROUP BY route_id HAVING COUNT(*) > 10;`],
  ["Trips with >20 stops", ["stop_times"], `SELECT trip_id, COUNT(*) FROM stop_times GROUP BY trip_id HAVING COUNT(*) > 20;`],
  ["Duplicate route names", ["routes"], `SELECT route_long_name, COUNT(DISTINCT route_id) FROM routes GROUP BY route_long_name HAVING COUNT(DISTINCT route_id) > 1;`],
  ["Busy stops", ["stop_times"], `SELECT stop_id, COUNT(*) FROM stop_times GROUP BY stop_id HAVING COUNT(*) > 50;`],
  ["Busy services", ["trips"], `SELECT service_id, COUNT(*) FROM trips GROUP BY service_id HAVING COUNT(*) > 100;`],
  ["Route type counts", ["routes"], `SELECT route_type, COUNT(*) FROM routes GROUP BY route_type;`],
  ["Stops grouped by name", ["stops"], `SELECT stop_name, COUNT(*) FROM stops GROUP BY stop_name;`],
  ["Trips per direction", ["trips"], `SELECT direction_id, COUNT(*) FROM trips GROUP BY direction_id;`],
  ["Duplicate stop names", ["stops"], `SELECT stop_name, COUNT(*) FROM stops GROUP BY stop_name HAVING COUNT(*) > 1;`],
  ["Stops per route", ["trips", "stop_times"], `SELECT t.route_id, COUNT(*) FROM stop_times st JOIN trips t ON st.trip_id = t.trip_id GROUP BY t.route_id;`],
  ["Trips with route names", ["routes", "trips"], `SELECT t.trip_id, r.route_long_name FROM trips t JOIN routes r ON t.route_id = r.route_id;`],
  ["Stop names per trip", ["stops", "stop_times"], `SELECT st.trip_id, s.stop_name FROM stop_times st JOIN stops s ON st.stop_id = s.stop_id;`],
  ["Trip with short name", ["routes", "trips"], `SELECT t.trip_id, r.route_short_name FROM trips t JOIN routes r ON t.route_id = r.route_id;`],
  ["Stop sequence for trip", ["stops", "stop_times"], `SELECT st.stop_sequence, s.stop_name FROM stop_times st JOIN stops s ON st.stop_id = s.stop_id WHERE st.trip_id = '1001' ORDER BY st.stop_sequence;`],
  ["Count stops per route", ["routes", "trips", "stop_times"], `SELECT r.route_id, COUNT(*) FROM routes r JOIN trips t ON r.route_id = t.route_id JOIN stop_times st ON t.trip_id = st.trip_id GROUP BY r.route_id;`],
];